/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 6;
  /** RegularExpression Id. */
  int COMENTARIO_MULTILINEA = 7;
  /** RegularExpression Id. */
  int ENTERO = 8;
  /** RegularExpression Id. */
  int DECIMAL = 9;
  /** RegularExpression Id. */
  int SI = 10;
  /** RegularExpression Id. */
  int SINO = 11;
  /** RegularExpression Id. */
  int SELECTOR = 12;
  /** RegularExpression Id. */
  int SELECCION = 13;
  /** RegularExpression Id. */
  int AUTOMATICO = 14;
  /** RegularExpression Id. */
  int PARA = 15;
  /** RegularExpression Id. */
  int MIENTRAS = 16;
  /** RegularExpression Id. */
  int ROMPER = 17;
  /** RegularExpression Id. */
  int LEER = 18;
  /** RegularExpression Id. */
  int IMPRIMIR = 19;
  /** RegularExpression Id. */
  int PRINCIPAL = 20;
  /** RegularExpression Id. */
  int ENTEROS = 21;
  /** RegularExpression Id. */
  int DECIMALES = 22;
  /** RegularExpression Id. */
  int CADENA = 23;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 24;
  /** RegularExpression Id. */
  int LETRA = 25;
  /** RegularExpression Id. */
  int NUMERO = 26;
  /** RegularExpression Id. */
  int MAS = 27;
  /** RegularExpression Id. */
  int MENOS = 28;
  /** RegularExpression Id. */
  int MULTIPLICACION = 29;
  /** RegularExpression Id. */
  int DIVISION = 30;
  /** RegularExpression Id. */
  int MODULO = 31;
  /** RegularExpression Id. */
  int IGUAL = 32;
  /** RegularExpression Id. */
  int IGUALQUE = 33;
  /** RegularExpression Id. */
  int DIFERENTEDE = 34;
  /** RegularExpression Id. */
  int MENORQUE = 35;
  /** RegularExpression Id. */
  int MAYORQUE = 36;
  /** RegularExpression Id. */
  int MENORIGUAL = 37;
  /** RegularExpression Id. */
  int MAYORIGUAL = 38;
  /** RegularExpression Id. */
  int O = 39;
  /** RegularExpression Id. */
  int Y = 40;
  /** RegularExpression Id. */
  int LLAVEA = 41;
  /** RegularExpression Id. */
  int LLAVEC = 42;
  /** RegularExpression Id. */
  int PARENTESISA = 43;
  /** RegularExpression Id. */
  int PARENTESISC = 44;
  /** RegularExpression Id. */
  int PUNTOCOMA = 45;
  /** RegularExpression Id. */
  int DOSPUNTOS = 46;
  /** RegularExpression Id. */
  int CONCATENACION = 47;
  /** RegularExpression Id. */
  int ERROR = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMENTARIO_LINEA>",
    "<COMENTARIO_MULTILINEA>",
    "\"entero\"",
    "\"decimal\"",
    "\"si\"",
    "\"si no\"",
    "\"selector\"",
    "\"seleccion\"",
    "\"automatico\"",
    "\"para\"",
    "\"mientras\"",
    "\"romper\"",
    "\"leer\"",
    "\"imprimir\"",
    "\"principal\"",
    "<ENTEROS>",
    "<DECIMALES>",
    "<CADENA>",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<NUMERO>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"||\"",
    "\"&&\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\"<<\"",
    "<ERROR>",
  };

}
